### ISSUE TITLE
Unnecessary script searching for "console"

### ISSUE THREAD

**Issue by Saniol** [uCreateit/react-native-innovator#11]
https://github.com/uCreateit/react-native-innovator/blob/3067b1f3fcc45938ed9c70183e136355bd03b744/Innovator/scripts/checkForbiddenWords.js#L55

If you'd like to forbid commiting `console` calls, you can easily do that with this ESLint rule https://eslint.org/docs/rules/no-console

**Comment by AbdoHema2016** [comment]
This was made as an example, will change to the eslint rule and add the "UNSAFE_"  instead for deprecated react methods
