### ISSUE TITLE
Replace class components with functional

### ISSUE THREAD

**Issue by Saniol** [uCreateit/react-native-innovator#15]
https://github.com/uCreateit/react-native-innovator/blob/3067b1f3fcc45938ed9c70183e136355bd03b744/Innovator/src/components/CButton/index.js#L5

you can find nicely explained reasons for that in our React coding guidelines: https://github.com/uCreateit/coding-guidelines/tree/master/React#functional-components-1

**Comment by p3420a1** [comment]
#33 #

**Comment by p3420a1** [comment]
Replaced the class components with function under #33

**Comment by ajaykumar97** [comment]
Closing the issue as it has been fixed in #33
