### ISSUE TITLE
Unable to resolve module react-native-size-matters

### ISSUE THREAD

**Issue by pankiljoshi** [uCreateit/react-native-innovator#40]
I encountered this error while following default setup process:

`error: Error: Unable to resolve module react-native-size-matters from \src\components\Loader\style.js: react-native-size-matters could not be found within the project or in these directories:
  node_modules`

**Comment by pankiljoshi** [comment]
Resolved it by adding the package `yarn add react-native-size-matters`.

**Comment by ajaykumar97** [comment]
@pankiljoshi Thanks for reporting the issue. It has been resolved in the PR #43 .
